#
# Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2020-Present Datadog, Inc.
#
org.gradle.jvmargs=-Xmx2560m
android.useAndroidX=true
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true
# TODO RUM-17797 Support built-in Kotlin and new AGP DSL
# We still want to apply the Kotlin version specified by us
android.builtInKotlin=false
android.newDsl=false

# Leave the next line blank for CI
