/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 */

package com.datadog.gradle.plugin

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Injects the build ID file into the merged assets directory via AGP's artifact transform API.
 */
abstract class InjectBuildIdToAssetsTask : DefaultTask() {

    /**
     * The current merged assets directory provided by AGP.
     */
    @get:InputDirectory
    abstract val inputAssets: DirectoryProperty

    /**
     * The output assets directory where AGP expects the result.
     */
    @get:OutputDirectory
    abstract val outputAssets: DirectoryProperty

    /**
     * The build ID file generated by [GenerateBuildIdTask].
     */
    @get:InputFile
    abstract val buildIdFile: RegularFileProperty

    init {
        description = "Injects Datadog build ID into the application assets."
    }

    /**
     * Executes task action: copies the existing assets and adds build ID asset on top.
     */
    @TaskAction
    fun inject() {
        val inputDir = inputAssets.get().asFile
        val outputDir = outputAssets.get().asFile
        outputDir.mkdirs()

        inputDir.copyRecursively(outputDir, overwrite = true)

        check(buildIdFile.isPresent && buildIdFile.get().asFile.exists()) {
            "Cannot inject Datadog build ID into the assets, because it doesn't exist."
        }

        buildIdFile.get().asFile.copyTo(
            File(outputDir, GenerateBuildIdTask.BUILD_ID_FILE_NAME),
            overwrite = true
        )
    }
}
