/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2020-Present Datadog, Inc.
 */

package com.datadog.gradle.plugin

import com.datadog.gradle.plugin.internal.utils.capitalizeChar
import com.datadog.gradle.plugin.internal.variant.AppVariant
import fr.xgouchet.elmyr.Case
import fr.xgouchet.elmyr.annotation.StringForgery
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.mockito.kotlin.doReturn
import org.mockito.kotlin.mock
import org.mockito.kotlin.whenever

internal class DdAndroidGradlePluginWarnUnknownVariantsTest : DdAndroidGradlePluginTestBase() {

    // region findUnknownVariantConfigNames

    @Test
    fun `M return empty set W findUnknownVariantConfigNames() { no configured variants }`() {
        // Given
        whenever(mockVariant.flavors) doReturn fakeFlavorNames
        whenever(mockVariant.buildTypeName) doReturn fakeBuildTypeName
        whenever(fakeExtension.variants.names) doReturn sortedSetOf()

        // When
        val result = testedPlugin.findUnknownVariantConfigNames(fakeExtension, listOf(mockVariant))

        // Then
        assertThat(result).isEmpty()
    }

    @Test
    fun `M return empty set W findUnknownVariantConfigNames() { name matches full variant }`(
        @StringForgery(case = Case.LOWER) flavor: String
    ) {
        // Given
        val fullName = flavor + fakeBuildTypeName.replaceFirstChar { capitalizeChar(it) }
        whenever(mockVariant.flavors) doReturn listOf(flavor)
        whenever(mockVariant.buildTypeName) doReturn fakeBuildTypeName
        whenever(fakeExtension.variants.names) doReturn sortedSetOf(fullName)

        // When
        val result = testedPlugin.findUnknownVariantConfigNames(fakeExtension, listOf(mockVariant))

        // Then
        assertThat(result).isEmpty()
    }

    @Test
    fun `M return empty set W findUnknownVariantConfigNames() { name matches flavor only }`(
        @StringForgery(case = Case.LOWER) flavor: String
    ) {
        // Given
        whenever(mockVariant.flavors) doReturn listOf(flavor)
        whenever(mockVariant.buildTypeName) doReturn fakeBuildTypeName
        whenever(fakeExtension.variants.names) doReturn sortedSetOf(flavor)

        // When
        val result = testedPlugin.findUnknownVariantConfigNames(fakeExtension, listOf(mockVariant))

        // Then
        assertThat(result).isEmpty()
    }

    @Test
    fun `M return empty set W findUnknownVariantConfigNames() { name matches build type only }`() {
        // Given
        whenever(mockVariant.flavors) doReturn fakeFlavorNames
        whenever(mockVariant.buildTypeName) doReturn fakeBuildTypeName
        whenever(fakeExtension.variants.names) doReturn sortedSetOf(fakeBuildTypeName)

        // When
        val result = testedPlugin.findUnknownVariantConfigNames(fakeExtension, listOf(mockVariant))

        // Then
        assertThat(result).isEmpty()
    }

    @Test
    fun `M return empty set W findUnknownVariantConfigNames() { name valid across multiple variants }`(
        @StringForgery(case = Case.LOWER) flavor: String
    ) {
        // Given - same flavor name exists in two variants with different build types
        val anotherMockVariant = mock<AppVariant>()
        whenever(mockVariant.flavors) doReturn listOf(flavor)
        whenever(mockVariant.buildTypeName) doReturn "debug"
        whenever(anotherMockVariant.flavors) doReturn listOf(flavor)
        whenever(anotherMockVariant.buildTypeName) doReturn "release"
        whenever(fakeExtension.variants.names) doReturn sortedSetOf(flavor)

        // When
        val result = testedPlugin.findUnknownVariantConfigNames(
            fakeExtension,
            listOf(mockVariant, anotherMockVariant)
        )

        // Then
        assertThat(result).isEmpty()
    }

    @Test
    fun `M return typo name W findUnknownVariantConfigNames() { configured name has no matching variant }`() {
        // Given
        // TYPO_VARIANT_NAME contains uppercase mid-word letters, which VariantIterator
        // can never produce when all flavor names are lowercase alphabetical strings
        // (generated by @StringForgery(case = Case.LOWER)) and build types are
        // one of debug/preRelease/release.
        whenever(mockVariant.flavors) doReturn fakeFlavorNames
        whenever(mockVariant.buildTypeName) doReturn fakeBuildTypeName
        whenever(fakeExtension.variants.names) doReturn sortedSetOf(TYPO_VARIANT_NAME)

        // When
        val result = testedPlugin.findUnknownVariantConfigNames(fakeExtension, listOf(mockVariant))

        // Then
        assertThat(result).containsExactly(TYPO_VARIANT_NAME)
    }

    @Test
    fun `M return only typo names W findUnknownVariantConfigNames() { mix of valid and typo names }`(
        @StringForgery(case = Case.LOWER) flavor: String
    ) {
        // Given
        whenever(mockVariant.flavors) doReturn listOf(flavor)
        whenever(mockVariant.buildTypeName) doReturn fakeBuildTypeName
        whenever(fakeExtension.variants.names) doReturn sortedSetOf(flavor, TYPO_VARIANT_NAME)

        // When
        val result = testedPlugin.findUnknownVariantConfigNames(fakeExtension, listOf(mockVariant))

        // Then
        assertThat(result).containsExactly(TYPO_VARIANT_NAME)
    }

    @Test
    fun `M return all names W findUnknownVariantConfigNames() { no known variants }`() {
        // Given
        whenever(fakeExtension.variants.names) doReturn sortedSetOf(TYPO_VARIANT_NAME)

        // When
        val result = testedPlugin.findUnknownVariantConfigNames(fakeExtension, emptyList())

        // Then
        assertThat(result).containsExactly(TYPO_VARIANT_NAME)
    }

    @Test
    fun `M return multiple typo names W findUnknownVariantConfigNames() { all configured names are typos }`(
        @StringForgery(case = Case.LOWER) flavor: String
    ) {
        // Given
        val typo1 = "typoVariantAlpha"
        val typo2 = "typoVariantBeta"
        whenever(mockVariant.flavors) doReturn listOf(flavor)
        whenever(mockVariant.buildTypeName) doReturn fakeBuildTypeName
        whenever(fakeExtension.variants.names) doReturn sortedSetOf(typo1, typo2)

        // When
        val result = testedPlugin.findUnknownVariantConfigNames(fakeExtension, listOf(mockVariant))

        // Then
        assertThat(result).containsExactlyInAnyOrder(typo1, typo2)
    }

    // endregion

    companion object {
        // TYPO_VARIANT_NAME deliberately contains uppercase mid-word letters.
        // VariantIterator.buildVariantName() only capitalizes the first letter of tokens
        // after the first, producing patterns like "flavorBuildtype". Since all forge-generated
        // flavor names are lowercase alphabetical (@StringForgery(case = Case.LOWER)) and build
        // types are one of {debug, preRelease, release}, no combination can ever produce a name
        // with uppercase letters in the middle of the FIRST token — making this name
        // guaranteed safe as a "typo" across all randomised test inputs.
        private const val TYPO_VARIANT_NAME = "typoVariantThatDoesNotExist"
    }
}
